#!/usr/bin/env python
# -*- encoding: utf-8 -*-
"""
Concourse in resource
"""
# Python 2 and 3 compatibility
from __future__ import unicode_literals

import os.path
import sys

from resource import Resource


class FiaasDeployment(Resource):
    """Concourse resource implementation for FIAAS Deployment"""

    def __init__(self, *args, **kwargs):
        super(self.__class__, self).__init__(*args, **kwargs)

    def fetch(self, folder, source, version, params):
        """Return last version from 'out' resource"""
        metadata = []
        rvalue = {"version": version, "metadata": metadata}
        rcode = 0
        return rcode, rvalue

if __name__ == '__main__':
    r = FiaasDeployment()
    try:
        rcode = r.run(os.path.basename(__file__))
    except Exception as e:
        sys.stderr.write("ERROR: " + str(e) + "\n")
        sys.exit(1)
    sys.exit(rcode)
